[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fractal_printer"
version = "0.1.0"
description = "My fractal printer"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["."]
